global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  receiver: 'email-me'


receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitriy_mamontov'

- name: 'email-me'
  email_configs:
  - to: pearl4003@gmail.com
    from: pearl4003@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "pearl4003@gmail.com"
    auth_identity: "pearl4003@gmail.com"
    auth_password: "supersecret"
