version: '3.3'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  fluentd:
    #build: ../logging/fluentd/
    image: mamontov/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.8.3
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.8.3
    ports:
      - "8080:5601"

