{
 "title": "UI Service monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "UI HTTP resuests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "uui_request_count" }
   ]
  },
  {
   "title": "Rate of UI HTTP Requests with Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "http responce time 95 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, ui_request_latency_seconds_bucket{path=\"/\"})"
    }
   ]
  }
 ]
}