---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      name: ui
      labels:
        app: ui
    spec:
      containers:
      - image: artemmkin/ui
        name: ui
        ports:
        - containerPort: 9292
        env:
        - name: POST_SERVICE_HOST
          value: "post"
        - name: POST_SERVICE_PORT
          value: "5000"
        - name: COMMENT_SERVICE_HOST
          value: "comment"
        - name: COMMENT_SERVICE_PORT
          value: "9292"
