
    labels:
      app: reddit
      component: ui
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: reddit
        component: ui
    template:
      metadata:
        name: ui-pod
        labels:
          app: reddit
          component: ui
      spec:
        containers:
        - image: mamontov/ui
          name: ui
          env:
          - name: ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
