---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      name: ui
      labels:
        app: ui
    spec:
      containers:
        image: artemmkin/ui
        environment:
          - POST_SERVICE_HOST=post
          - POST_SERVICE_PORT=5000
          - COMMENT_SERVICE_HOST=comment
          - COMMENT_SERVICE_PORT=9292
        ports:
          - "9292:9292"
        depends_on:
          - post
        name: ui
