- hosts: app
  user: appuser
  become_method: sudo
  vars:
    token: kZWyuzETE_WBv2sj7xaj
    url: http://35.232.149.22/
  tasks:
    - name: download runner
      shell: curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
      become: true

    - name: change +x
      file:
        path: /usr/local/bin/gitlab-runner
        mode: +x
      become: true

    - name: add user
      user:
        name: gitlab-runner
        shell: /bin/bash

    - name: install runner
      shell: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
      become: true

    - name: start runner
      shell: gitlab-runner start
      become: true

    - name: register runner
      shell: gitlab-runner register --url="{{ url }}" --registration-token="{{ token }}"
      become: true
