---
- name: prepare docekr
  hosts: all
  become: true
  tasks:
    - name: prepare
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: add docekr repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: add keys
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: install docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: enabled docker
      systemd:
        name: docker
        enabled: yes
        state: restarted

#    - name: start app container
#      docker_container:
#        name: reddit-app
#        image: mamontov/otus-reddit
#        ports:
#          - "9292:9292"

    - name: run docker container
      shell: sudo docker run -d --rm -p 9292:9292 mamontov/otus-reddit:1.0
